//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=frootaxi_db;Persist Security Info=True;User" +
            " ID=frootaxiUser")]
        public string frootaxi_dbConnectionString {
            get {
                return ((string)(this["frootaxi_dbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("workstation id=frootaxi.mssql.somee.com;packet size=4096;user id=JemymaRC_SQLLogi" +
            "n_1;pwd=y1oqckbvjx;data source=frootaxi.mssql.somee.com;persist security info=Fa" +
            "lse;initial catalog=frootaxi")]
        public string frootaxi_dbConnectionString1 {
            get {
                return ((string)(this["frootaxi_dbConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=frootaxi_db;Persist Security Info=True;User" +
            " ID=frootaxiUser;Password=frootaxipswd")]
        public string frootaxi_dbConnectionString2 {
            get {
                return ((string)(this["frootaxi_dbConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=frootaxi_db;User ID=frootaxiUser;Password=f" +
            "rootaxiUser")]
        public string frootaxi_dbConnectionString3 {
            get {
                return ((string)(this["frootaxi_dbConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=frootaxi_db;User ID=frootaxiUser;Password=f" +
            "rootaxipswd")]
        public string frootaxi_dbConnectionString4 {
            get {
                return ((string)(this["frootaxi_dbConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ftdb.c4inkcnkde3g.us-east-1.rds.amazonaws.com;Initial Catalog=frootax" +
            "i_db;User ID=frootaxiMastUser;Password=frootaxipswd211")]
        public string frootaxi_dbConnectionString5 {
            get {
                return ((string)(this["frootaxi_dbConnectionString5"]));
            }
        }
    }
}
